name: CI

on: [push, pull_request]

jobs:
  mod:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: HEMTT Build
        uses: docker://hemtt/hemtt:0.7.6
        with:
          entrypoint: hemtt
          args: build --release

      - name: Upload mod
        uses: actions/upload-artifact@v1
        with:
          name: 'mod'
          path: releases/1.0.0/@asp

  extension-linux:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y g++-multilib

      - name: Build Linux 32 bit
        run: mkdir build-linux32 && cd build-linux32 && cmake -DCMAKE_BUILD_TYPE=Release .. && make

      - name: Upload Linux 32 bit
        uses: actions/upload-artifact@v1
        with:
          name: ArmaScriptProfiler.so
          path: build-linux32/src/ArmaScriptProfiler.so

  extension-windows:
    runs-on: windows-2019
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build Windows 64 bit
        run: mkdir build-win64 && cd build-win64 && cmake -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A x64 .. && cmake --build . --config Release

      - name: Upload Windows 64 bit
        uses: actions/upload-artifact@v1
        with:
          name: ArmaScriptProfiler_x64.dll
          path: release/@ArmaScriptProfiler/intercept/Release/ArmaScriptProfiler_x64.dll

  package:
    runs-on: ubuntu-18.04
    needs:
      - extension-linux
      - extension-windows
      - mod
    steps:
      - name: Download mod
        uses: actions/download-artifact@v1
        with:
          name: 'mod'
          path: '@ArmaScriptProfiler'

      - name: Download Linux 32 bit
        uses: actions/download-artifact@v1
        with:
          name: ArmaScriptProfiler.so
          path: '@ArmaScriptProfiler/intercept/'

      - name: Download Windows 64 bit
        uses: actions/download-artifact@v1
        with:
          name: ArmaScriptProfiler_x64.dll
          path: '@ArmaScriptProfiler/intercept/'

      - name: Upload built mod
        uses: actions/upload-artifact@1.0.0
        with:
          name: '@ArmaScriptProfiler'
          path: '.'
